# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-22 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180822_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='poll',
            new_name='question',
        ),
    ]
